name: Run Test

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  Integration:
    runs-on: macos-13
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.1'
      - name: Build Package
        run: swift build
      - name: Run Tests
        run: swift test